/*
 This Java source file was generated by the Gradle 'init' task.
*/

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
// import static org.mockito.Mockito.mock;
// import static org.mockito.ArgumentMatchers.any;
// import static org.mockito.ArgumentMatchers.anyInt;
// import static org.mockito.BDDMockito.then;
// import static org.mockito.Mockito.times;
// import static org.mockito.BDDMockito.given;
// import org.mockito.Mock;

public class PopulationCounterTest {

    
    //Testing the PopulationCounter Class with out mocking 
    @Test
    public void testSomeLibraryMethod() throws Exception {

        // Setup
        String expected = "World population is: 1347982728";
        // https://stackoverflow.com/questions/8708342/redirect-console-output-to-string-in-java
        ByteArrayOutputStream baos = new ByteArrayOutputStream(); 
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        System.out.flush();

        // Exercise
        PopulationCounter.main(new String[0]);

        // Assert
        String output = baos.toString();
        assertEquals( expected, output );

        // Teardown
        System.setOut(old);
    
    }


    @Test
    public void FetchingFileTest() throws Exception{
        // assertEquals(1,2);
        
    }

}
